version: "3"
   
services:
  redis:
    image: redis

    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      
    environment: 
      - REDIS_HOST=redis