# Generated by Django 3.1.6 on 2021-02-19 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
