# Generated by Django 3.1.6 on 2021-02-19 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_enddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='endDate',
            new_name='dueDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.AddField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
